# .github/workflows/install-noomiclone.yml
name: Install NoomiClone files

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Unity WebGL files
        run: |
          mkdir -p noomiclone
          cd noomiclone
          curl -L -o webgl.4.data.unityweb \
            "https://github.com/Camerons-Git7/FoodCases/releases/download/files/webgl.4.data.unityweb"
          curl -L -o webgl.4.wasm.code.unityweb \
            "https://github.com/Camerons-Git7/FoodCases/releases/download/files/webgl.4.wasm.code.unityweb"
          curl -L -o webgl.4.wasm.framework.unityweb \
            "https://github.com/Camerons-Git7/FoodCases/releases/download/files/webgl.4.wasm.framework.unityweb"
          ls -lh

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: noomiclone-build
          path: noomiclone/
