name: Replace Favicon URL

on:
  workflow_dispatch:
  push:

jobs:
  replace-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace favicon URL
        run: |
          find . -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" -o -name "*.json" -o -name "*.txt" \) -exec sed -i 's|https://i.ibb.co/MD6zN5z1/6-E8-D76-F3-B9-FD-4-A69-B35-D-451484-BC75-AC.png|https://math.hws.edu/favicon.ico|g' {} +

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .
          git diff --cached --quiet || git commit -m "Replace favicon URL"

      - name: Push changes
        run: git push
